//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LS.Widgets.Birthdays {
    using System.Web.UI.WebControls.Expressions;
    using System.Web.UI.HtmlControls;
    using System.Collections;
    using System.Text;
    using System.Web.UI;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Linq;
    using Microsoft.SharePoint.WebPartPages;
    using System.Web.SessionState;
    using System.Configuration;
    using Microsoft.SharePoint;
    using System.Web;
    using System.Web.DynamicData;
    using System.Web.Caching;
    using System.Web.Profile;
    using System.ComponentModel.DataAnnotations;
    using System.Web.UI.WebControls;
    using System.Web.Security;
    using System;
    using Microsoft.SharePoint.Utilities;
    using System.Text.RegularExpressions;
    using System.Collections.Specialized;
    using System.Web.UI.WebControls.WebParts;
    using Microsoft.SharePoint.WebControls;
    
    
    public partial class Birthdays {
        
        public static implicit operator global::System.Web.UI.TemplateControl(Birthdays target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControlTree(global::LS.Widgets.Birthdays.Birthdays @__ctrl) {
            @__ctrl.SetRenderMethodDelegate(new System.Web.UI.RenderMethod(this.@__Render__control1));
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__Render__control1(System.Web.UI.HtmlTextWriter @__w, System.Web.UI.Control parameterContainer) {
            @__w.Write("\r\n\r\n<!--css-->\r\n<link href=\"");
    @__w.Write( SPContext.Current.Site.ServerRelativeUrl.TrimEnd('/')  );

            @__w.Write("/style library/ls.widgets/birthdays/birthdays.min.css\" rel=\"stylesheet\">\r\n\r\n<!-- " +
                    "load necessary scripts-->\r\n<script src=\"");
     @__w.Write( SPContext.Current.Site.ServerRelativeUrl.TrimEnd('/') );

            @__w.Write(@"/style library/ls.widgets/base/utilities.js""></script>

<script>
    //momentjs
    LS.SP.Utilities.EnsureScript(window.moment, ""//cdnjs.cloudflare.com/ajax/libs/moment.js/2.8.4/moment.min.js"");

    //jQuery
    LS.SP.Utilities.EnsureScript(window.jQuery, ""//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.1/jquery.min.js"");

    //handlebars
    LS.SP.Utilities.EnsureScript(window.handlebars, ""//cdnjs.cloudflare.com/ajax/libs/handlebars.js/2.0.0/handlebars.min.js"");
</script>

<script src=""");
     @__w.Write( SPContext.Current.Site.ServerRelativeUrl.TrimEnd('/') );

            @__w.Write("/style library/ls.widgets/base/handlebars-helpers.js\"></script>\r\n<script src=\"");
     @__w.Write( SPContext.Current.Site.ServerRelativeUrl.TrimEnd('/') );

            @__w.Write(@"/style library/ls.widgets/birthdays/birthdays.js""></script>

<script id=""birthdays-template"" type=""text/x-handlebars-template"">
    {{#each Birthdays}}

    <div class=""birthday-item clearfix"">

        <div class=""birthday-photo"">
            <div class=""photo-content"">
                <a href=""{{Path}}"">
                <img src=""{{PhotoUrl}}"" /></a>
            </div>            
        </div>

        <div class=""birthday-info"">

             <h2 class=""name""><a href=""{{Path}}"">{{Name}}</a></h2>
             <h3 class=""birthday"">{{Birthday}}{{#if BirthdayIsToday}}&nbsp;{{YearsString}}{{/if}}</h3>

            {{#if BirthdayIsToday}}
                <input type=""text"" class=""happy-birthday-wish"" data-user=""{{AccountName}}"" data-name=""{{FirstName}}"" placeholder=""{{Placeholder}}"" />
            {{else}}
                <div class=""years-string"">{{YearsString}}</div>
            {{/if}}
        </div>

    </div>

    {{/each}}
</script>

<div id=""bdays_");
       @__w.Write( this.ID );

            @__w.Write("\" class=\"birthdays-container\">\r\n    <h3>Loading \r\n        <img src=\"");
          @__w.Write( SPContext.Current.Site.ServerRelativeUrl.TrimEnd('/') );

            @__w.Write("/_layouts/15/images/gears_anv4.gif\" /></h3>\r\n</div>\r\n\r\n<script>\r\n    var eleId = " +
                    "\'bdays_");
               @__w.Write( this.ID );

            @__w.Write("\';\r\n\r\n    jQuery(\'#\' + eleId).SPBirthdays(\r\n                ");
        @__w.Write( GetJSOptions() );

            @__w.Write("\r\n            );\r\n\r\n</script>\r\n");
        }
        
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
